name: row_city
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: 4.0.4
  url_launcher: ^6.3.0
  path_provider: 2.1.3
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.4
  html: ^0.15.0
  get: ^4.6.1

flutter:
  uses-material-design: true
  assets: 
    - assets/images/

flutter_icons:
  image_path: "rowCityLogo.png"
  android: true
  adaptive_icon_foreground: "rowCityLogo.png"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  windows:
    generate: true
    image_path: "rowCityLogo.png"
    icon_size: 48